name: automatic release
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: ci
        run: npm ci
      - name: release
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
